### ISSUE TITLE
Am I right in interpretation

### ISSUE THREAD

**Issue by beginner984** [ncborcherding/ccRCC#2]
Hello

I just started following codes in this page because for my scRNA-seq analysis seems very helpful, but I need help please if possible

I have a subclusters of B cells 

![Rplot34](https://user-images.githubusercontent.com/43682980/133984985-e87bddbd-62d8-4f3e-8365-dd8c2ee396f1.png)
![Rplot](https://user-images.githubusercontent.com/43682980/133984998-127224eb-d56a-4a53-af04-24206df6b538.png)
![Rplot01](https://user-images.githubusercontent.com/43682980/133985008-9140f2e1-b2cc-4116-a2c8-53d6b949aa6c.png)
![Rplot02](https://user-images.githubusercontent.com/43682980/133985805-2b64c2da-4e75-4284-8acb-5ba7c193c206.png)

I done trajectory analysis by your code but I can not see the root 

[Trajectory2_pseudotime.pdf](https://github.com/ncborcherding/ccRCC/files/7194918/Trajectory2_pseudotime.pdf)
[Trajectory2_pseudotime.pdf](https://github.com/ncborcherding/ccRCC/files/7194929/Trajectory2_pseudotime.pdf)
[Trajectory.pdf](https://github.com/ncborcherding/ccRCC/files/7194930/Trajectory.pdf)
[Trajectory2.pdf](https://github.com/ncborcherding/ccRCC/files/7194931/Trajectory2.pdf)

Am I right in interpretation that sub-cluster 7 is the end of trajectory and sub-cluster 11 is the root?

Based on the marker genes likely sub-cluster 7 is mature B cells and sub-cluster 11 for plasblasts 

Please correct me if I am on the wrong way

Thanks a million in advance

**Comment by ncborcherding** [comment]
Hey Beginner984, 

The root is something you can define in the ```slingshot()``` call using the **start.clus = X**. The term root iteself is a part of a minimal-spanning tree language, however, slingshot does not use it, so there will be no root. Without defining a start or stop cluster, ```slingshot()``` will infer them, so it might require some prior knowledge like mature vs immature to interpret. It can easily happen that the trajectory is reversed though.

One thing I might recommend is instead of just subsetting the B cells from the whole experiment, I might reintegrate/recluster  7 and 11 to see if there are additional information or clusters of B cells. 

Nick

**Comment by beginner984** [comment]
Hello and thank you again for this repository 

I have a small Seurat object of PBMC

```
> mono
An object of class Seurat 
60396 features across 753 samples within 3 assays 
Active assay: RNA (36601 features, 2000 variable features)
 2 other assays present: SCT, integrated
 2 dimensional reductions calculated: pca, umap
> 
```

I want to do ssGSEA, so

```
> library(escape)
> sign <- read.delim("immune_sign.txt")[,1:20]
> full <- as.list(sign)
> unique <- names(full) 
> list <- list()
> for (i in seq_along(unique)) {
+     tmp <- full[[i]]
+     tmp <- tmp[tmp != ""]
+     tmp <- unique(toupper(tmp))
+     tmp <- GSEABase::GeneSet(tmp, setName=paste(unique[i]))
+     list[[i]] <- tmp
+     
+ }
> list <- GSEABase::GeneSetCollection(list)
> ES2 <- enrichIt(obj = mono, gene.sets = list, groups = 1000, cores = 2)
[1] "Using sets of 1000 cells. Running 1 times."
Setting parallel calculations through a SnowParam back-end
with workers=2 and tasks=100.
Estimating ssGSEA scores for 20 gene sets.
> GS <- getGeneSets(library = c("H", "C5"))
```

But this part almost takes forever :(

```
> ES <- enrichIt(mono, gene.sets = GS, groups = 1000, cores = 4)
[1] "Using sets of 1000 cells. Running 1 times."
Setting parallel calculations through a SnowParam back-end
with workers=4 and tasks=100.
Estimating ssGSEA scores for 15018 gene sets.
```


Is there a way to push this part to be complete? To speed that? Might be I am doing something wrong somewhere?

Thanks a lot for any help

**Comment by ncborcherding** [comment]
> But this part almost takes forever :(
> 
> > ES <- enrichIt(mono, gene.sets = GS, groups = 1000, cores = 4)
> [1] "Using sets of 1000 cells. Running 1 times."
> Setting parallel calculations through a SnowParam back-end
> with workers=4 and tasks=100.
> Estimating ssGSEA scores for 15018 gene sets.

So I doubt you are doing something wrong, the length of the enrichment calculation will be based on the number of cells and the number of gene sets. You are calculating normalized enrichment scores for ~1000 cells * 15,018 gene sets. Depending on your system, it will take a while. You can minimize the length of time by possibly selecting/filtering your gene sets. 

Sorry for the inconvenience - a newer version of escape also implemented the [Ucell](https://github.com/carmonalab/UCell) that substantially increases the speed. You can check out the more [updated vignette](https://ncborcherding.github.io/vignettes/escape_vignette.html#4_Enrichment) too if you're interested. 

Nick
