### ISSUE TITLE
Which data is used for sub clustering?

### ISSUE THREAD

**Issue by f6v** [ncborcherding/ccRCC#3]
Hi, Nick!

First off, I want to say again that it's an incredibly useful repository!

I'm a bit confused though. If I understand correctly, the workflow looks like:
1. SCTransform all the samples
2. Run integration
3. Cluster, UMAP, etc.
4. Normalize RNA assay
5. Use normalised RNA assay values to find markers
6. ...
7. Load the Seurat object
8. Strip everything except RNA assay
9. Select CD8 cells
9. SCTransform each sample
10. Integrate just the CD8 cells
...

At point 9, you're applying SCTransform to the RNA data. But that's the data already normalised with `NormalizeData` in step 4:
https://github.com/ncborcherding/ccRCC/blob/7119c2dc903dde6d41e9a4a112a47746fd6396f3/CD8.Tcells.Rmd#L275

Am I missing something? Is step 9 meant to be run on raw expression values?

Best

**Comment by ncborcherding** [comment]
Hey F6v,

Nice catch -  no you are correct, the ```SCTransform()``` and ```NormalizeData()``` will run off of the RNA count assay information. ```SCTransform()``` however will store the resulting normalization in the **sct assay**.  Here, the ```NormalizeData()``` is not needed and does not affect any of the downstream analysis. 

Let me know if you have any other questions,
Nick

**Comment by f6v** [comment]
Thanks for getting back to me!

I think I might not have explained what exactly I meant. When this line runs on the `RNA` assay:
https://github.com/ncborcherding/ccRCC/blob/7119c2dc903dde6d41e9a4a112a47746fd6396f3/CD8.Tcells.Rmd#L73
The `data` slot has the normalised values, since you ran `NormalizeData()` on it before calling `FindAllMarkers`. What I'm not sure about is whether `SCTransform` will now use the `data` slot with the normalised counts or the raw counts.

**Comment by ncborcherding** [comment]
Oh sorry - to clarify, ```SCTransform()``` is not going to pull the data from the output of ```NormalizeData()``` but from the raw counts itself.

**Comment by f6v** [comment]
Thank you for clarification!
