### ISSUE TITLE
No available Code

### ISSUE THREAD

**Issue by amirshams84** [ncborcherding/ccRCC#4]
Is there anyplace where we can access the R code that generated mentioned plot?

**Comment by ncborcherding** [comment]
All available in the .Rmd (Rmarkdown files) in the repository

![image](https://user-images.githubusercontent.com/22754118/191323035-753b8fc1-3314-4c54-ba6c-2dd28689e705.png)

**Comment by amirshams84** [comment]
Thanks
closing the ticket
