### ISSUE TITLE
Cluster Biomarker analysis uses "RNA" assay instead of "integrated" or "SCT" 

### ISSUE THREAD

**Issue by amirshams84** [ncborcherding/ccRCC#5]
Hi 
Obviously, this is a question, not a bug, I just wonder why you chose RNA assay instead of integrated

Thanks

DefaultAssay(Tcells) <- "RNA"

**Comment by ncborcherding** [comment]
In general - I used the integrated assay for the dimensional reduction and the RNA assay for differential gene expression/cell cycle regression/expression visualization. At the time of writing this code, there was no method for using SCT or integrated values to perform differential gene expression (there is now with the PrepSCTMarkers() function). 

Nick

**Comment by amirshams84** [comment]
Thanks, very helpful
